version: '3.8' 

services:
  db:
    ports:
      - "27017:27017"

  api:
    command: "npm run dev"
    ports:
      - "${API_PORT}:${API_PORT}"
    volumes:
      - "./src/api/routes:/app/routes/"
      - "./src/api/controllers:/app/controllers/"
      - "./src/api/server.js:/app/server.js"
      - "./src/api/db.js:/app/db.js"
      - "./src/schemas:/app/schemas"
      - "./src/utils:/app/utils"
