FROM node:16

WORKDIR /app

COPY package*.json ./

RUN npm install

RUN npm install nodemon

RUN mkdir node_modules/.cache && chmod -R 777 node_modules/.cache

RUN npm config set cache node_modules/.cache

COPY . .

CMD ["npm", "run", "dev"]
